### ISSUE TITLE
Creating Docker version

### ISSUE THREAD

**Issue by lolouk44** [jshridha/anovamaster#5]
Hi,

I'm just starting using your repo and wanted to check a few things.
I've got my anova connected and I can user it as a "sensor" for now, in that Home Assistant displays the Anova's status correctly.
I don't seem able to send commands though. 
Are you still using the anova with your repo?

By the way I'm also working on a docker container version of your code.
https://github.com/lolouk44/anovamaster
and
https://hub.docker.com/repository/docker/lolouk44/anovamaster

**Comment by lolouk44** [comment]
ignore above. I stupidly forgot an import on the MQTTController file... 
All working fine now.

**Comment by jshridha** [comment]
OK great! And thanks for working on the docker. I was planning to do that next and just haven't gotten to it yet. I'd greatly appreciate any PRs once you get that up and running.

**Comment by lolouk44** [comment]
Hi Jay,

Good to hear back from you 😄 
I've made quite a few changes, It'll give you some some night reading 😉 
I'm doing the final changes and testing the container to see if I need to build for different architectures/platforms.
I'll submit a PR in the next few days I suspect.
The next goal for me is to try and migrate to python3 if possible as python2 is no longer supported...
We probably also need to update the doc as it wasn't clear at first how it works (like the timer only being sent to the Anova if it's on)
if you're ok with the above I'll create a few "issues" to track changes and enhancements. Do you have time to test?

**Comment by jshridha** [comment]
@lolouk44 We already have python3 (readme needs to be updated to reflect that). I'd happily accept any doc update PRs. We can leverage docker buildx and azure pipelines to build for different architectures. Something similar to this would work: https://github.com/jshridha/inkbird/blob/master/azure-pipelines.yml

**Comment by lolouk44** [comment]
By the way I have added the changes from the 2 PRs that @mikeage created. You probably should merge them first?
Yeah I was planning on using buildx to create a manifest with multi-arch.
Was planning on creating these: to cover standard desktop style and raspberry pi from 2 to 4
1. linux/amd64
1. linux/arm32v6
1. linux/arm32v7
1. linux/arm64v8

**Comment by lolouk44** [comment]
for python3 I had issues running it so stuck with python2. Have you tested it?

**Comment by jshridha** [comment]
Yes, I've been running it with python3 without problem.

> By the way I have added the changes from the 2 PRs that @mikeage created. You probably should merge them first?
> Yeah I was planning on using buildx to create a manifest with multi-arch.
> Was planning on creating these: to cover standard desktop style and raspberry pi from 2 to 4
> 
> 1. linux/amd64
> 2. linux/arm32v6
> 3. linux/arm32v7
> 4. linux/arm64v8

Merged!

**Comment by jshridha** [comment]
> for python3 I had issues running it so stuck with python2. Have you tested it?

Yeah I've been running it without issue.

**Comment by lolouk44** [comment]
Thanks I'll have another go and will update the dockerfile to reflect then

**Comment by jshridha** [comment]
Let me know if you run into issues and I'll share the configuration I'm using. Thanks a lot for the help! This project definitely needs a little face lift!

**Comment by lolouk44** [comment]
Can you do me a favour a test the docker container?
It's still on python 2 but should work. Then I can do a PR with all the changes.
https://hub.docker.com/repository/docker/lolouk44/anovamaster

**Comment by lolouk44** [comment]
just pushed my multi-arch manifest to docker hub, closing this thread
