### ISSUE TITLE
Python3 issues

### ISSUE THREAD

**Issue by lolouk44** [jshridha/anovamaster#7]
Hi Jay,

Looking at python3 now.
did this on a fresh git clone (with a copy of my config):
```
  $ virtualenv venv
  $ . venv/bin/activate
  $ pip3 install -r requirements.txt
  $ python3 run.py
```
and I get this error:
```
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    main()
  File "run.py", line 14, in main
    my_anova = AnovaMaster(config)
  File "/home/cctv/Anova/anova_old/anovamaster/AnovaMaster/AnovaMaster.py", line 32, in __init__
    self._anova = RESTAnovaController(self._config.get('anova', 'mac'), connect = False)
  File "/home/cctv/Anova/anova_old/anovamaster/AnovaMaster/RESTAnovaController.py", line 24, in __init__
    super(RESTAnovaController, self).__init__(mac_address, connect=connect)
TypeError: __init__() got an unexpected keyword argument 'connect'
```

**Comment by jshridha** [comment]
Which version of python3 are you on? It's working for me on python 3.7.3

**Comment by jshridha** [comment]
Also, which version of pycirculate are you using? You'll need the version on master here:
https://github.com/CY8s/pycirculate

**Comment by lolouk44** [comment]
Thanks.
`Python 3.7.7` and `pycirculate-0.1.1a1`

**Comment by jshridha** [comment]
Really strange. Looking through the source code for pycirculate, connect is definitely an argument. Can you load up a python shell, import pycirculate, and make sure the path it references has the connect argument?

```
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycirculate
>>> pycirculate
<module 'pycirculate' from '/home/pi/git/anovamaster/.venv/lib/python3.7/site-packages/pycirculate/__init__.py'>
```

**Comment by lolouk44** [comment]
Oh you found it. For some reason I did not have the same code as in the repo.
Overwritten and it works.
I guess I need to stop messing about with my system, hence the driving to create a docker version of your code 😆 
I'll start working on a docker container that uses python3.
In the meantime let me know if the current container works for you.
Thanks
